services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend  
      
  data_miner:
    build: ./data_miner
    restart: always
    depends_on: 
      - postgres
    environment:
      DB_PATH: ${DB_PATH}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CRON_NEW: ${CRON_NEW}
      CRON_UPDATE: ${CRON_UPDATE}
    ports:
      - "8080:8080"
    networks:
      - backend
      
  telegram_data_miner:
    build: ./telegram_data_miner
    restart: always
    depends_on: 
      - postgres
    environment:
      DB_PATH: ${DB_PATH}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_NAME: ${BOT_NAME}
      BOT_PIN: ${BOT_PIN}
      BASE_URL: ${BASE_URL}
      CRONE_NOTIF: ${CRONE_NOTIF}
    ports:
      - "8081:8080"
    networks:
      - backend
      
volumes:
  postgres_data:
networks:
  backend:  